apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: scaletestapp
  endpoints:
    - port: http
      path: /metrics
      interval: 5s
      scrapeTimeout: 5s