worker_processes auto;

events {
  worker_connections 1024;
}

http {
  default_type text/plain;

  limit_req_zone $binary_remote_addr zone=req_limit:10m rate=10r/m;
  limit_req_status 429;

  upstream backend_servers {
    server 127.0.0.1:8081;
    server 127.0.0.1:8082;
    server 127.0.0.1:8083;
  }

  server {
    listen 80;

    location / {
      limit_req zone=req_limit burst=5 nodelay;

      proxy_pass http://backend_servers;
    }
  }

  server {
    listen 8081;
    location / {
      return 200 "backend1\n";
    }
  }

  server {
    listen 8082;
    location / {
      return 200 "backend2\n";
    }
  }

  server {
    listen 8083;
    location / {
      return 200 "backend3\n";
    }
  }
}

